### ISSUE TITLE
hhvm-dev not installable on 12.04 (precise)

### ISSUE THREAD

**Issue by jwatzman** [hhvm/packaging#113]
See logs on https://github.com/facebook/hhvm/issues/5142

**Comment by jwatzman** [comment]
I'll have to try this on precise myself when I get a chance, not sure when I'll get around to it.

**Comment by awartani** [comment]
same on 14.04

**Comment by fredemmott** [comment]
This class of problems is fixed in the new WIP nightly system (see https://github.com/hhvm/packaging/issues/128#issuecomment-342037825 ) - built on a clean system, runtime depends are inferred from build-depends; if something's wrong with the package name/version, we won't have the required build dependencies, so it'll fail to build.
